### ISSUE TITLE
Websockets Error: not opened

### ISSUE THREAD

**Issue by sanoel** [OADA/oada-srvc-docker#18]
Using the oada-cache with a websocket connection, I'm seeing regular `Error: not opened` errors in the logs.
```http-handler           | Thu, 10 Oct 2019 16:19:29 GMT websockets:websockets:error Error: not opened
http-handler           |     at WebSocket.send (/code/http-handler/oada-srvc-http-handler/node_modules/ws/lib/WebSocket.js:358:18)
http-handler           |     at /code/http-handler/oada-srvc-http-handler/websockets.js:249:18
http-handler           |     at processImmediate (timers.js:632:19)
http-handler           | From previous event:
http-handler           |     at WebSocket.message (/code/http-handler/oada-srvc-http-handler/websockets.js:156:22)
http-handler           |     at WebSocket.emit (events.js:182:13)
http-handler           |     at Receiver._receiver.onmessage (/code/http-handler/oada-srvc-http-handler/node_modules/ws/lib/WebSocket.js:146:54)
http-handler           |     at Receiver.dataMessage (/code/http-handler/oada-srvc-http-handler/node_modules/ws/lib/Receiver.js:389:14)
http-handler           |     at Receiver.getData (/code/http-handler/oada-srvc-http-handler/node_modules/ws/lib/Receiver.js:330:12)
http-handler           |     at Receiver.startLoop (/code/http-handler/oada-srvc-http-handler/node_modules/ws/lib/Receiver.js:165:16)
http-handler           |     at Receiver.add (/code/http-handler/oada-srvc-http-handler/node_modules/ws/lib/Receiver.js:139:10)
http-handler           |     at Socket._ultron.on (/code/http-handler/oada-srvc-http-handler/node_modules/ws/lib/WebSocket.js:142:22)
http-handler           |     at Socket.emit (events.js:182:13)
http-handler           |     at addChunk (_stream_readable.js:287:12)
http-handler           |     at readableAddChunk (_stream_readable.js:268:11)
http-handler           |     at Socket.Readable.push (_stream_readable.js:223:10)
http-handler           |     at TCP.onStreamRead (internal/stream_base_commons.js:122:17)```

**Comment by awlayton** [comment]
Fixed in #51
