### ISSUE TITLE
Handle error from node-rdkafka

### ISSUE THREAD

**Issue by tomohiroarakawa** [OADA/oada-srvc-docker#40]
After running `oada-srvc-docker` for about a week, many microservices became unresponsive after printing the following error messages. It seems that those errors came from `node-rdkafka`.

write-handler:
```
write-handler          | 2020-01-21T05:46:06.797530903Z events.js:170
write-handler          | 2020-01-21T05:46:06.797540789Z       throw er; // Unhandled 'error' event
write-handler          | 2020-01-21T05:46:06.797544949Z       ^
write-handler          | 2020-01-21T05:46:06.797548796Z Error: Local: Timed out
write-handler          | 2020-01-21T05:46:06.797552450Z Emitted 'error' event at:
write-handler          | 2020-01-21T05:46:06.797556205Z     at KafkaConsumer.Base.consumer.on.args (/code/libs/oada-lib-kafka/base.js:81:19)
write-handler          | 2020-01-21T05:46:06.797560589Z     at KafkaConsumer.emit (events.js:198:15)
write-handler          | 2020-01-21T05:46:06.797564332Z     at eventHandler (/code/libs/oada-lib-kafka/node_modules/node-rdkafka/lib/client.js:69:16)
```

graph-lookup:
```
graph-lookup           | 2020-01-21T05:46:06.519322817Z events.js:170
graph-lookup           | 2020-01-21T05:46:06.519351028Z       throw er; // Unhandled 'error' event
graph-lookup           | 2020-01-21T05:46:06.519375999Z       ^
graph-lookup           | 2020-01-21T05:46:06.519381041Z Error: Local: Timed out
graph-lookup           | 2020-01-21T05:46:06.519385448Z Emitted 'error' event at:
graph-lookup           | 2020-01-21T05:46:06.519396382Z     at KafkaConsumer.Base.consumer.on.args (/code/libs/oada-lib-kafka/base.js:81:19)
graph-lookup           | 2020-01-21T05:46:06.519407118Z     at KafkaConsumer.emit (events.js:198:15)
graph-lookup           | 2020-01-21T05:46:06.519411742Z     at eventHandler (/code/libs/oada-lib-kafka/node_modules/node-rdkafka/lib/client.js:69:16)
```

permissions-handler:
```
permissions-handler    | 2020-01-21T05:46:05.423401911Z events.js:170
permissions-handler    | 2020-01-21T05:46:05.423408579Z       throw er; // Unhandled 'error' event
permissions-handler    | 2020-01-21T05:46:05.423412601Z       ^
permissions-handler    | 2020-01-21T05:46:05.423416323Z Error: Local: Timed out
permissions-handler    | 2020-01-21T05:46:05.423419943Z Emitted 'error' event at:
permissions-handler    | 2020-01-21T05:46:05.423423641Z     at KafkaConsumer.Base.consumer.on.args (/code/libs/oada-lib-kafka/base.js:81:19)
permissions-handler    | 2020-01-21T05:46:05.423427794Z     at KafkaConsumer.emit (events.js:198:15)
permissions-handler    | 2020-01-21T05:46:05.423431679Z     at eventHandler (/code/libs/oada-lib-kafka/node_modules/node-rdkafka/lib/client.js:69:16)
```

**Comment by awlayton** [comment]
This should be fixed. Services will now restart on kafka error. Please reopen if you see it stuck there again.
