### ISSUE TITLE
Websockets: PUT of a string

### ISSUE THREAD

**Issue by cyrusbowman** [OADA/oada-srvc-docker#41]
Doing a PUT over a websocket to an existing key with a string for data returns a 500 with a VPackError.

> ArangoError: VPackError error: Expecting digit
    at new ArangoError (/code/libs/oada-lib-arangodb/node_modules/arangojs/lib/error.js:30:15)
    at /code/libs/oada-lib-arangodb/node_modules/arangojs/lib/connection.js:204:21
    at callback (/code/libs/oada-lib-arangodb/node_modules/arangojs/lib/util/request.node.js:52:9)
    at IncomingMessage.<anonymous> (/code/libs/oada-lib-arangodb/node_modules/arangojs/lib/util/request.node.js:63:11)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

**Comment by sanoel** [comment]
We'll leave this open because the true issue here is a poor error message. If previous experience is correct, take this error to mean your JSON isn't formatted correctly.

**Comment by abalmos** [comment]
Shouldn't a string `JSON.parse`?

**Comment by sanoel** [comment]
Should. I'll have to see the request.

**Comment by sanoel** [comment]
According to @awlayton, arango is the problem here. JSON needs to be an object or array. Should be able to come up with a fix on our side.

**Comment by abalmos** [comment]
@awlayton it works with insomnia ?

Andrew

**Comment by awlayton** [comment]
With what string though?

**Comment by abalmos** [comment]
Like PUT:
`/bookmarks/trelliwfw/documents/abc123/_meta/services/blah/tasks/123/status"
BODY: "complete"

Andrew
